services:
  - type: web
    name: p2p-secure-lend
    env: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn secure_lend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: true
      - key: SUPABASE_URL
        value: https://ffxdkifwaxgaojlyppmg.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmeGRraWZ3YXhnYW9qbHlwcG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzNDg2MzYsImV4cCI6MjA4OTkyNDYzNn0.8m_1HB9ZYCQeZayj46j7qMZR75NFjnVhGOkf_O01SV8