# Generated by Django 6.0.3 on 2026-03-24 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_collateral_verified_by_customuser_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='agent_verified_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value verified by agent', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='contract_pdf',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('id_front_image', models.CharField(blank=True, max_length=500, null=True)),
                ('id_back_image', models.CharField(blank=True, max_length=500, null=True)),
                ('selfie_image', models.CharField(blank=True, max_length=500, null=True)),
                ('signature_image', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ai_verification_result', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kycs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
