# Generated by Django 6.0.3 on 2026-03-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_collateral_agent_verified_value_loan_contract_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='id_back_image',
            field=models.CharField(blank=True, help_text='Image path (Pillow not available)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='id_front_image',
            field=models.CharField(blank=True, help_text='Image path (Pillow not available)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='selfie_image',
            field=models.CharField(blank=True, help_text='Image path (Pillow not available)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='signature_image',
            field=models.CharField(blank=True, help_text='Image path (Pillow not available)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='contract_pdf',
            field=models.CharField(blank=True, help_text='File path (Pillow not available)', max_length=500, null=True),
        ),
    ]
